### ISSUE TITLE
Слышб работать

### ISSUE THREAD

**Issue by mashed-potatoes** [mishailovic/motya#6]
```
ERROR:root:Command failed
Traceback (most recent call last):
  File "/home/telegram/friendly-telegram/friendly-telegram/main.py", line 151, in handle_command
    await func(message)
  File "<string>", line 82, in motyacmd
  File "/home/telegram/friendly-telegram/friendly-telegram/compat/util.py", line 91, in wrapper
    return self.__convert(await ret)
  File "/home/telegram/.local/lib/python3.6/site-packages/telethon/client/downloads.py", line 357, in download_media
    media, file, date, thumb, progress_callback
  File "/home/telegram/.local/lib/python3.6/site-packages/telethon/client/downloads.py", line 694, in _download_photo
    progress_callback=progress_callback
  File "/home/telegram/.local/lib/python3.6/site-packages/telethon/client/downloads.py", line 458, in download_file
    input_location, request_size=part_size, dc_id=dc_id):
  File "/home/telegram/.local/lib/python3.6/site-packages/telethon/requestiter.py", line 75, in __anext__
    if await self._load_next_chunk():
  File "/home/telegram/.local/lib/python3.6/site-packages/telethon/client/downloads.py", line 61, in _load_next_chunk
    cur = await self._request()
  File "/home/telegram/.local/lib/python3.6/site-packages/telethon/client/downloads.py", line 71, in _request
    result = await self._sender.send(self.request)
telethon.errors.rpcerrorlist.FileIdInvalidError: The provided file id is invalid (caused by GetFileRequest)
ERROR:telethon.client.updates:Unhandled exception on functools.partial(<function handle_command at 0xb4fc7660>, <friendly-telegram.loader.Modules object at 0xb472c9b0>, <friendly-telegram.database.frontend.Database object at 0xb4814a78>)
Traceback (most recent call last):
  File "/home/telegram/.local/lib/python3.6/site-packages/telethon/client/updates.py", line 431, in _dispatch_update
    await callback(event)
  File "/home/telegram/friendly-telegram/friendly-telegram/main.py", line 159, in handle_command
    raise e
  File "/home/telegram/friendly-telegram/friendly-telegram/main.py", line 151, in handle_command
    await func(message)
  File "<string>", line 82, in motyacmd
  File "/home/telegram/friendly-telegram/friendly-telegram/compat/util.py", line 91, in wrapper
    return self.__convert(await ret)
  File "/home/telegram/.local/lib/python3.6/site-packages/telethon/client/downloads.py", line 357, in download_media
    media, file, date, thumb, progress_callback
  File "/home/telegram/.local/lib/python3.6/site-packages/telethon/client/downloads.py", line 694, in _download_photo
    progress_callback=progress_callback
  File "/home/telegram/.local/lib/python3.6/site-packages/telethon/client/downloads.py", line 458, in download_file
    input_location, request_size=part_size, dc_id=dc_id):
  File "/home/telegram/.local/lib/python3.6/site-packages/telethon/requestiter.py", line 75, in __anext__
    if await self._load_next_chunk():
  File "/home/telegram/.local/lib/python3.6/site-packages/telethon/client/downloads.py", line 61, in _load_next_chunk
    cur = await self._request()
  File "/home/telegram/.local/lib/python3.6/site-packages/telethon/client/downloads.py", line 71, in _request
    result = await self._sender.send(self.request)
telethon.errors.rpcerrorlist.FileIdInvalidError: The provided file id is invalid (caused by GetFileRequest)
```
Я все сказал.

**Comment by mishailovic** [comment]
А ты кто? (Who?)

А если по серьезному то к 15:00 проснется деменкоп и посмотрит что не так. Я грешу на архитектуру проца

**Comment by mashed-potatoes** [comment]
Картошка.
Сомневаюсь что виновата архитектура.
Сейчас попытаюсь отдебажить `file id`

**Comment by mishailovic** [comment]
Ежели получится фиксануть то кидай пул реквест, я приму

**Comment by mashed-potatoes** [comment]
![image](https://user-images.githubusercontent.com/37037851/79552716-d557ef80-80b4-11ea-855b-4add35d384e8.png)
Кстати, модуль пишет в папку с ботом. Надо бы перенести в `/tmp`. Или еще куда-нибудь.

**Comment by mashed-potatoes** [comment]
Проблема умерла вместе в Orange Pi One.
